### ISSUE TITLE
Running generation just waits

### ISSUE THREAD

**Issue by niksy** [fraserxu/electron-pdf#11]
I’m trying to create PDF from simple text file but when I run electron-pdf, my terminal process just waits and I can only exit it with Ctrl+C.

I’m not using global installation, but running it with npm script which access’ local installation of electron-pdf.

Is this a known issue?

**Comment by fraserxu** [comment]
Are you testing against a `.txt` file? This is not included yet since there's no format.

**Comment by niksy** [comment]
My bad, it’s a simple `.html` file (body contains "Hello world" as content).

**Comment by thiphariel** [comment]
Up.

Same issue here, global install, test with HTML or Markdown file, but my term is just "waiting", nothing happened...

**Comment by aminmeyghani** [comment]
Same here ...

**Comment by jeffutter** [comment]
Same here. Is there any way to get process/debugging output?

**Comment by fraserxu** [comment]
Hi guys, sorry for the later response. 

I dig into the code for a while and finally find the bug. There's nothing wrong with my code but a package.json causing an issue. 

This issue is caused by the code setting the `process.title https://github.com/sindresorhus/meow/blob/master/index.js#L58

```JavaScript
process.title = pkg.bin ? Object.keys(pkg.bin)[0] : pkg.name;
```

It's also part of a known electron bug https://github.com/atom/electron/issues/1412 

It's a nearly impossible to debug but fortunately I found it. I'll probably switch to a new library and fix it later today.

**Comment by fraserxu** [comment]
Hi guys, I fixed this issue and pushed to v0.6.1. 

If you have further issue, please let me know, thanks!

**Comment by aminmeyghani** [comment]
:+1:

**Comment by aminmeyghani** [comment]
:+1:
