### ISSUE TITLE
How to display full viewport?

### ISSUE THREAD

**Issue by Tin-Nguyen** [fraserxu/electron-pdf#188]
I'm trying to switch to use `electron-pdf` lib from `phantomJS`. I can generate the PDF from my HTML page, however, I don't know how to modify the viewport to make the UI in PDF is generated correctly.

<img width="1392" alt="screen shot 2017-04-27 at 3 04 36 pm" src="https://cloud.githubusercontent.com/assets/5414916/25499937/2d0bfd78-2b5b-11e7-860f-82a7f7e765e6.png">

Please see the screenshot, even I set 'landscape', the UI still be rendered incorrectly. I want to make the viewport of page to be larger, which options will I use to do it?

**Comment by codecounselor** [comment]
First of all, try version 1.2.1 which uses Electron 1.4.x.  I recently noticed really bad stuff like what you're seeing after upgrading to version 1.3 of electron-pdf which is using Electron 1.6.x.

If you want the browser window to be larger, than you will have to set custom sizes, for example `--pageSize '{"width":304800,"height":228600}'` (that is 9x12 inches).  I'd recommend you take a look at the `windowTailor.js` file https://github.com/fraserxu/electron-pdf/blob/master/lib/windowTailor.js

You need to be fairly intentional about either designing your document to be responsive or increasing your output size.  If you want stuff to export well onto Letter size PDFs then you'll need to render your page into an appropriately sized window (816 x 1056)

The code emits lots of events that you can use to see what it is doing.  It is also helpful to set `--browserConfig '{"show":true,"x":0,"y":0}'` because what shows up in the window may not be what you get in your PDF.

Running directly from the CLI will be a bit more challenging to debug, but you could hack some of the code to leave the Electron process running if you want to pike around in the Chromium browser manually.

**Comment by Tin-Nguyen** [comment]
I checked with version 1.2.1 use Electron 1.4.15. However there is no change to fix the issue. I also tried to use `--pageSize '{"width":304800,"height":228600}'` and tried the larger numbers, the UI still be broken, the document's viewport seems cannot be scaled out when we increase the pageSize. The function works well on PhantomJS and Chrome. Any ideas?

**Comment by wkw** [comment]
This is just a shot in the dark, but if you're testing on a server, could it be related to Xvfb's display size?

**Comment by codecounselor** [comment]
That's actually a decent theory.  If that proves to be the case there is a setting `enableLargerThanScreen` on the BrowserWindow that you could try passing.  Here is the Electron documentation https://electron.atom.io/docs/api/browser-window/

**Comment by wkw** [comment]
Ok.. so if it's a possibility, I'll toss this out too....
 I've just spent the lasts few days figuring out this headless rendering for electron-pdf and before that [electron-screenshot-service](https://github.com/FWeinb/electron-screenshot-service). Without knowing in depth what effects the `-screen` setting  has on the final rendering, this is how I'm firing up my app:

```
[ENV SETTINGS...] xvfb-run -a --server-args='-fbdir /tmp/ -screen 0 1680x1050x24' ./node_modules/electron/cli.js build/server.js
```

I'm doing this in a Docker container at moment for testing.

**Comment by Tin-Nguyen** [comment]
we have resolved it. Closed the issue now

**Comment by codecounselor** [comment]
@Tin-Nguyen can you please post the solution here so others can benefit from it? Thanks!

**Comment by Tin-Nguyen** [comment]
Here is my solution:
We use the command to generate the PDF with landscape
`electron-pdf <input> <output> -l --marginsType '0'`

Also, we update the layout of webpage to have full viewport.
