### ISSUE TITLE
TypeError : fs.existsSync is not a function

### ISSUE THREAD

**Issue by steric85** [fraserxu/electron-pdf#194]
I have created an app using create-react-app and installed electron-pdf. I have used the code given in [issue #183](https://github.com/fraserxu/electron-pdf/issues/183) by @midweststudios.
By doing so, I am getting an error:
`TypeError: fs.existsSync is not a function`
How shall I solve this error?

**Comment by fraserxu** [comment]
I don't have enough context of how and where you use it. 

But as far as I know create-react-app is a rather `client`(browser) thing, and all the related webpack config for bundling ES6 code is for browser only, so when it reads `fs.existsSync` it will break because there's no `fs` in browser. You can probably adjust the webpack config but I don't think it will work as expected.

**Comment by steric85** [comment]
Actually I want to convert HTML to PDF using `electron-pdf`. I don't want to achieve this using command line. Instead I want to write a javascript code as I also want the rendered React components to be a part of the pdf. Can you guide me to achieve this please?

**Comment by fraserxu** [comment]
The way to achieve this is heavily depends on the setup you have. If you are not using it from command line, you need to have at least a **node.js server** running somewhere you can require this module and call related apis.

Please provide more context of what your current setup is, and what is your user story to generate PDF.

**Comment by steric85** [comment]
I am using:
OS:  macOS Sierra
node version : 6.10.3
npm version: 4.6.1

I want to use `create-react-app` to make an app such that for a component:
```
....some code above...
render() {
  return <div>This should come in a pdf</div>;
}
...some code below...
```
we can see the output in pdf just like the way it is seen in the browser.

**Comment by codecounselor** [comment]
As @fraserxu already mentioned, Electron requires Node.js.  You can't use this project to create PDF exports from inside a web browser.  Which since you're mentioning React is what I assume you are hoping for.

My use case is probably similar to yours and I run a separate Node.JS API Server **inside** of the Electron process so that it can perform exports.  My web application sends HTTP Posts to this server and gets the PDFs back which it then forwards along to the client.  This is ideal because you get consistent behavior in every browser your users may choose to use.

I'm closing this issue, as it's not supported.
