### ISSUE TITLE
Add printDelay 

### ISSUE THREAD

**Issue by sarunks** [fraserxu/electron-pdf#31]
I was having a requirement to add printDelay as many charts are involved in my url which takes time to load.

**Comment by burningTyger** [comment]
same here, I have failover images that replace missing images. In my pdf they are just missing and not replaced.

**Comment by destegabry** [comment]
Is it possible to use the electron's waitForJS option? I think is a better option instead of sleep for a fixed amount of time.

**Comment by fraserxu** [comment]
I don't think waitForJS could help us here as it's not about loading script but wait for async data request.

I think doing server side rendering might be a better option but need more work to do if you are not doing.

**Comment by destegabry** [comment]
I need to render a bunch of highcharts on a PDF server side.
I wouldn't like to run a separate process to convert them to images then
embed on the HTML.

In this case it should be better to wait for a global JS var that would be
set by the chart plot callback.

With your solution a the code must be written in the server app instead of
the template JS, so the render task would be less agnostic.


Il giorno mer 14 set 2016 alle 02:34 Fraser Xu <notifications@github.com>
ha scritto:

**Comment by codecounselor** [comment]
So there is now support for both an explicit wait, and waiting for an event to be emitted from document.body of the loaded page.  Are these two features not enough to deal with the use cases listed in this issue?

Side note: I had a similar use case of converting pages into images (and put into a pptx file).  I found the `pdf2images-multiple` module to come in handle.  You can [see it used here](https://github.com/SpiderStrategies/pdf-powerpoint/blob/master/lib/powerpoint.js), it does require some packages be installed (i.e. ImageMagick)

**Comment by codecounselor** [comment]
the `waitForJSEvent` option is available in version 0.13.0
