### ISSUE TITLE
Support for pageSize

### ISSUE THREAD

**Issue by Reggino** [fraserxu/electron-pdf#75]
This is awesome, thanks for this!

Right now the only thing i am missing is `pageSize` support. 

I did notice this added recently to  electron. [https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsprinttopdfoptions-callback](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsprinttopdfoptions-callback) [https://github.com/electron/electron/issues/5747] (https://github.com/electron/electron/issues/5747)

It would be nice to use this feature!

**Comment by abhijithcs** [comment]
@fraserxu Is there an option to pass the pageSize from the renderer process to the main process? So that the page width can be dynamically set? #14292

**Comment by codecounselor** [comment]
You can do that using https://github.com/fraserxu/electron-pdf#observing-your-own-event

You will find this line in `exportJob.js`
`const dim = WindowTailor.setWindowDimensions(this.window, this.args.pageSize, landscape)`

I believe if you modify the example to set `pageSize` instead of `landscape` you should be able to achieve your goal.

```javascript
job.observeReadyEvent( (detail) => {
    return new Promise( (resolve,reject) => {
      if( detail && detail.landscape ){
        job.changeArgValue('pageSize', putYourNewValueHere)
      }
      resolve()
    })
})
```
